# Generated by Django 6.0.4 on 2026-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('viendo', 'Viendo'), ('visto', 'Visto'), ('dropeado', 'Dropeado'), ('whitelist', 'Whitelist')], default='viendo', max_length=20)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('episodios_totales', models.PositiveIntegerField(default=0)),
                ('episodios_vistos', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('api_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
