# Generated by Django 6.0.4 on 2026-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('viendo', 'Viendo'), ('visto', 'Visto'), ('dropeado', 'Dropeado'), ('whitelist', 'Whitelist')], default='viendo', max_length=20)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
