# Generated by Django 6.0.4 on 2026-05-12 15:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_alter_review_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anime',
            unique_together={('user', 'api_id')},
        ),
    ]
