events {}

http {
    upstream django_backend {
        server web:8000;
    }

    server {
        listen 80;
        server_name yoursideanime.tech www.yoursideanime.tech;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            proxy_pass http://django_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
