# Bloque obligatorio para el funcionamiento de nginx
events {}

http {
    include /etc/nginx/mime.types; # Para proporcionar archivos estáticos correctamente
    default_type application/octet-stream; # Por defecto si no se reconoce
	
    server {
        listen 80; # Escuha tráfico HTTP
        server_name yoursideanime.duckdns.org; # Dominio
        return 301 https://$host$request_uri; # Redirección permanente a HTTPS
    }

    server {
        listen 443 ssl; # Escucha trafico HTTPS
        server_name yoursideanime.duckdns.org; # Dominio

        # Certificados SSL generador por Certbot
        ssl_certificate /etc/letsencrypt/live/yoursideanime.duckdns.org/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/yoursideanime.duckdns.org/privkey.pem;
	
	location /static/ {
	    alias /app/staticfiles/; # Ruta donde se guardan los archivos estáticos (Por Django)
	}	

        location / {
            proxy_pass http://web:8000; # Envía las peticiones al contenedor llamado "web"

            # Cabeceras para que Django detecte correctamente el host y protocolo
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
